apiVersion: v1
kind: Pod
metadata:
  name: ro
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.2"
        memory: "256Mi"
